# Generated by Django 2.0.3 on 2018-09-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regular_Pizza_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.FloatField(max_length=3)),
                ('large', models.FloatField(max_length=3)),
                ('pizza_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sicilian_Pizza_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.FloatField(max_length=3)),
                ('large', models.FloatField(max_length=3)),
                ('pizza_type', models.CharField(max_length=50)),
            ],
        ),
    ]
