# Generated by Django 2.0.3 on 2018-09-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180923_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regular_pizza_price',
            old_name='pizza_type',
            new_name='addition',
        ),
        migrations.RenameField(
            model_name='sicilian_pizza_price',
            old_name='pizza_type',
            new_name='addition',
        ),
    ]
