# Generated by Django 2.0.3 on 2018-09-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180923_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_toppings', models.CharField(max_length=65)),
            ],
        ),
    ]
