# Generated by Django 2.0.3 on 2018-09-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_toppings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regular_pizza_price',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='regular_pizza_price',
            table='Regular_Pizza_Price',
        ),
    ]
