# Generated by Django 2.0.3 on 2018-09-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180925_0933'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='regular_pizza_price',
            table='regular_pizza_price',
        ),
    ]
