# Generated by Django 2.0.3 on 2018-09-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180925_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regular_pizza_price',
            options={},
        ),
        migrations.AlterModelTable(
            name='regular_pizza_price',
            table=None,
        ),
    ]
