# Generated by Django 2.0.3 on 2018-09-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180925_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner_Platters_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('small', models.CharField(max_length=5)),
                ('large', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Dinner Platters Price',
            },
        ),
        migrations.AlterModelOptions(
            name='regular_pizza_price',
            options={'verbose_name': 'Regular pizza price', 'verbose_name_plural': 'Regular Pizza Prices'},
        ),
        migrations.AlterModelOptions(
            name='sicilian_pizza_price',
            options={'verbose_name': 'Sicilian pizza prices'},
        ),
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name': 'Available Toppings'},
        ),
    ]
