# Generated by Django 2.0.3 on 2018-09-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180926_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner_platters_price',
            name='large',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='dinner_platters_price',
            name='small',
            field=models.FloatField(max_length=5),
        ),
    ]
