# Generated by Django 2.0.3 on 2018-10-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_pasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('small', models.CharField(max_length=50)),
                ('large', models.CharField(max_length=50)),
            ],
        ),
    ]
