# Generated by Django 2.0.3 on 2018-10-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_sub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub',
            options={'verbose_name': 'Sub Price'},
        ),
        migrations.AlterField(
            model_name='sub',
            name='small',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
