# Generated by Django 2.0.3 on 2018-10-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20181003_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=5)),
            ],
            options={
                'verbose_name': 'Extras on Sub',
            },
        ),
    ]
